### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/pastry#1]
- [x] single file upload
- [x] if no extension default do plaintext
- [x] config for token
- [x] config to use autodetect if no extension
- [x] multi file upload (`pastry file1 file2 file3`)
- [x] directory upload
- [x] setting expires in time
- [x] private pastes
- [x] setting title
- [x] manually setting the lang
- [x] pretty help screen
- [x] default expires-in time
- [x] document readme
- [x] test on windows
- [ ] publish package to repos
